[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson@^7
    bodmer/TFT_eSPI
    Seeed-Studio/Seeed_Arduino_RoundDisplay

build_flags =
    -DUSER_SETUP_LOADED=1
    -DGFX_BL=-1
    -include src/tft_setup.h
